/**
 * Plesk Next.js Standalone Entry Point
 * 
 * This file serves as the startup file for Phusion Passenger on Plesk.
 * It redirects execution to the standalone Next.js server generated by 'next build'.
 * 
 * IMPORTANT: Ensure you have 'output: "standalone"' in your next.config.ts/js.
 */

const path = require('path');

// Set the production environment
process.env.NODE_ENV = 'production';

// Plesk/Passenger provides the port via process.env.PORT
// If not provided (local testing), fallback to 3000
process.env.PORT = process.env.PORT || 3000;

// Path to the standalone server.js
// Next.js creates this at .next/standalone/server.js
const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

console.log(`Starting Next.js standalone server from: ${standaloneServerPath}`);
console.log(`Environment: ${process.env.NODE_ENV}`);
console.log(`Port: ${process.env.PORT}`);

// Require the standalone server
// Next.js standalone server automatically starts listening when required.
try {
  require(standaloneServerPath);
} catch (error) {
  console.error('Failed to start Next.js standalone server:');
  console.error(error);
  process.exit(1);
}
